# GENERATED by packaging/packages.sh from dist/0.4.3/manifest.json.
# Do not edit: a hand-typed sha256 is a sha256 that is one release behind.
#
# Tap layout: this file lives in the repository `outcrawlai/homebrew-tap` at
# `Formula/outcrawl.rb`, which is what makes the install line work:
#
#   brew install outcrawlai/tap/outcrawl
#
# A binary formula rather than a source build: the artefact is already
# cross-compiled and verified, so `brew install` costs one download and needs no
# Go toolchain on the customer's machine.
class Outcrawl < Formula
  desc "Browser infrastructure for agents: scrape, crawl, search and agent runs"
  homepage "https://outcrawl.ai"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.4.3/outcrawl_0.4.3_darwin_arm64.tar.gz"
      sha256 "f7f5592d5235b697ea33f0e0c3cb59162c48efde8c2dd6de81ed0621e87bc12a"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.4.3/outcrawl_0.4.3_darwin_amd64.tar.gz"
      sha256 "e0829ef170e08fd221c6bb8a11ccdc5cd0490b437063cda272c8bdd0c9134f52"
    end
  end

  on_linux do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.4.3/outcrawl_0.4.3_linux_arm64.tar.gz"
      sha256 "4a5baa94e993c754236725784d8c72d2e0da4fee290004d715d78d37ce77c40c"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.4.3/outcrawl_0.4.3_linux_amd64.tar.gz"
      sha256 "710651ae71b8ac827ebc359dfc97d3ade4a820eba4b7b8f43ac530d877ba5394"
    end
  end

  def install
    bin.install "outcrawl"
  end

  test do
    # The version the formula claims, from the binary itself. A formula whose
    # bottle is a different release than its `version` is the failure this
    # catches, and it is one `brew test` away from being caught.
    assert_equal "0.4.3", shell_output("#{bin}/outcrawl --version").strip
    # And that the command surface loaded: the binary embeds its command tree,
    # so a build with a broken manifest exits non-zero here rather than at a
    # customer's first invocation.
    assert_match "browser infrastructure for agents", shell_output("#{bin}/outcrawl --help")
  end
end
