# GENERATED by packaging/packages.sh from dist/0.1.0/manifest.json.
# Do not edit: a hand-typed sha256 is a sha256 that is one release behind.
#
# Tap layout — this file lives in the repository `outcrawl/homebrew-tap` at
# `Formula/outcrawl.rb`, which is what makes the install line work:
#
#   brew install outcrawlai/tap/outcrawl
#
# A binary formula rather than a source build: the artefact is already
# cross-compiled and verified, so `brew install` costs one download and needs no
# Go toolchain on the customer's machine.
class Outcrawl < Formula
  desc "Browser infrastructure for agents: scrape, crawl, search and agent runs"
  homepage "https://outcrawl.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.1.0/outcrawl_0.1.0_darwin_arm64.tar.gz"
      sha256 "cf00808c1258f809b2ceb3b3ce3a0547485dccef43a407feedfa68da46f6cec6"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.1.0/outcrawl_0.1.0_darwin_amd64.tar.gz"
      sha256 "d743fc4b73348b254e520e0dbc9293bbdac429b291e6aa8adbf19049c2793829"
    end
  end

  on_linux do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.1.0/outcrawl_0.1.0_linux_arm64.tar.gz"
      sha256 "cdbba82241cc60f10ac66f143dbf2c52b2231535a5ffef45e2d5933f6b78b398"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.1.0/outcrawl_0.1.0_linux_amd64.tar.gz"
      sha256 "9265f8e64c7fb1e0df62cb641263c71a855ae1d17b0751b4369f3ea6959cc0a2"
    end
  end

  def install
    bin.install "outcrawl"
  end

  test do
    # The version the formula claims, from the binary itself. A formula whose
    # bottle is a different release than its `version` is the failure this
    # catches, and it is one `brew test` away from being caught.
    assert_equal "0.1.0", shell_output("#{bin}/outcrawl --version").strip
    # And that the command surface loaded: the binary embeds its command tree,
    # so a build with a broken manifest exits non-zero here rather than at a
    # customer's first invocation.
    assert_match "browser infrastructure for agents", shell_output("#{bin}/outcrawl --help")
  end
end
