# GENERATED by packaging/packages.sh from dist/0.4.6/manifest.json.
# Do not edit: a hand-typed sha256 is a sha256 that is one release behind.
#
# Tap layout: this file lives in the repository `outcrawlai/homebrew-tap` at
# `Formula/outcrawl.rb`, which is what makes the install line work:
#
#   brew install outcrawlai/tap/outcrawl
#
# A binary formula rather than a source build: the artefact is already
# cross-compiled and verified, so `brew install` costs one download and needs no
# Go toolchain on the customer's machine.
class Outcrawl < Formula
  desc "Browser infrastructure for agents: scrape, crawl, search and agent runs"
  homepage "https://outcrawl.ai"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.4.6/outcrawl_0.4.6_darwin_arm64.tar.gz"
      sha256 "4d97e54ddbb9d1cf39bb0ae8dc4880a17859ab5d9faba260dc0e85e66ca90ac7"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.4.6/outcrawl_0.4.6_darwin_amd64.tar.gz"
      sha256 "6490a8910f2244aba2e8e62ca0ad1e61c1c6f1b981427d644f195fa9e8b9fca6"
    end
  end

  on_linux do
    on_arm do
      url "https://get.outcrawl.ai/cli/0.4.6/outcrawl_0.4.6_linux_arm64.tar.gz"
      sha256 "467a1d0b5aa0ae00cf35c65e5375c47d3c0f0039c41ef3c45fc2275a0507ce1e"
    end
    on_intel do
      url "https://get.outcrawl.ai/cli/0.4.6/outcrawl_0.4.6_linux_amd64.tar.gz"
      sha256 "864f4e893058cda051d5dbc57298902d6db079329fc109fea5c2b95ae1a21c45"
    end
  end

  def install
    bin.install "outcrawl"
  end

  test do
    # The version the formula claims, from the binary itself. A formula whose
    # bottle is a different release than its `version` is the failure this
    # catches, and it is one `brew test` away from being caught.
    assert_equal "0.4.6", shell_output("#{bin}/outcrawl --version").strip
    # And that the command surface loaded: the binary embeds its command tree,
    # so a build with a broken manifest exits non-zero here rather than at a
    # customer's first invocation.
    assert_match "browser infrastructure for agents", shell_output("#{bin}/outcrawl --help")
  end
end
